//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VozDelEsteContext : DbContext
    {
        public VozDelEsteContext()
            : base("name=VozDelEsteContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Clima> Clima { get; set; }
        public virtual DbSet<ComentarioPrograma> ComentarioPrograma { get; set; }
        public virtual DbSet<Conductor> Conductor { get; set; }
        public virtual DbSet<CotizacionMoneda> CotizacionMoneda { get; set; }
        public virtual DbSet<Noticia> Noticia { get; set; }
        public virtual DbSet<Patrocinador> Patrocinador { get; set; }
        public virtual DbSet<Permiso> Permiso { get; set; }
        public virtual DbSet<Persona> Persona { get; set; }
        public virtual DbSet<Programacion> Programacion { get; set; }
        public virtual DbSet<ProgramaRadio> ProgramaRadio { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
